### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [torifat/nnvm#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by torifat** [comment]
@unixorn done. I hope  you don't have any problem with `MIT`.

**Comment by torifat** [comment]
I created another small plugin recently in case you like it - https://github.com/torifat/npms
